services:
  - type: web
    name: reviu-backend
    env: node
    rootDir: .
    buildCommand: npm install --legacy-peer-deps
    startCommand: node server.js
    envVars:
      - key: DB_HOST
        value: localhost
      - key: DB_USER
        value: root
      - key: DB_PASSWORD
        value: Jett108001@!
      - key: DB_NAME
        value: site_db
  - type: static
    name: reviu-frontend
    rootDir: frontend
    buildCommand: npm run build
    staticPublishPath: build
